# It is important to make sure you include the <bsd.kmod.mk> makefile
# after declaring the KMOD and SRCS variables

MAKEOBJDIR = .

# Declare Name of kernel module
KMOD    =  hello_fsm

# Enumerate Source files for kernel module
SRCS    =  hello_fsm.c

# Include kernel module makefile
.include <bsd.kmod.mk>
